### ISSUE TITLE
Redazione Verbale 25/11/2018 in Latex

### ISSUE THREAD

**Issue by sebacaccaro** [SWEightgroup/Colletta#14]

**Comment by sebacaccaro** [comment]
@BUGHopper22 Da revisionare

**Comment by gisachi** [comment]
@sebacaccaro 
![verbali-del_25-11-e-30-11](https://user-images.githubusercontent.com/23060660/49345562-e1d9d480-f686-11e8-884f-986e87c04ef0.JPG)
sistemare la cartella verbali,  aggiungere il file verbale_25-11-2018.tex nella cartella da creare "verbale del 25-11" che deve essere posizionata  al'interno della carterlla "verbali" dove dentro c'e' una cartella con il verbale del 30-11. e togliere il verbale-25-11-2018.pdf  che e' presente nella cartella "verbali".
