### ISSUE TITLE
Sezione Introduzione - Studio di fattibilità

### ISSUE THREAD

**Issue by DamienCg** [SWEightgroup/Colletta#15]

**Comment by gisachi** [comment]
@DamienCg  descrivere la scelta che abbiamo fatto nella parte introdutiva del documento non credo sia il massimo,  meglio descriverlo come tutti gli altri capitolati e alla fine fare una sezione conclusioni dove descrivi il perche del capitolato scelto. Togliere 1.2 Scopo del prodotto

**Comment by DamienCg** [comment]
> @DamienCg descrivere la scelta che abbiamo fatto nella parte introdutiva del documento non credo sia il massimo, meglio descriverlo come tutti gli altri capitolati e alla fine fare una sezione conclusioni dove descrivi il perche del capitolato scelto. Togliere 1.2 Scopo del prodotto

concordo, ti ho già risposto a riguardo

**Comment by gisachi** [comment]
verificato i 2 file sotto:
[https://github.com/SWEightgroup/Colletta/blob/ae5dc015d687f655165444ab1a6544bee3165b5d/RR%20-%20SWEight/studio_fattibilita/sez/C2.tex#L10](url)

riga 10: "...richiede realizzare..." credo vada qualcosa in mezzo tipo: "di"
riga 11: "...dati per fornire permettere a ricercatori/sviluppatori..." credo vada qualcosa in mezzo magari una virgola.
riga 6: elenchi puntati dobbiamo standartizzare la punteggiatura, tutti devono finire con ";" o l'ultimo elemento di ogni elenco con punto. (Ho visto su alcuni verbali dei vecchi progetti che lo hanno chiarito questo punto) da noi, in alcuni punti del documento e' in un modo in altri in un altro.
 
[https://github.com/SWEightgroup/Colletta/blob/ae5dc015d687f655165444ab1a6544bee3165b5d/RR%20-%20SWEight/studio_fattibilita/sez/introduzione.tex](url)
riga 3:  "...anche gli studi di fattibilità dei capitolati che sono stati scartati, mostrando anche..."
credo sia meglio evitare ripetere le stesse parole, "anche anche" nella stessa frase, riformulare.
riga 16: i link dei pdf  non sono clickabili, se non funzione solo a me, ignorare.

**Comment by DamienCg** [comment]
riga 6: elenchi puntati dobbiamo standartizzare la punteggiatura, tutti devono finire con ";" o l'ultimo elemento di ogni elenco con punto. (Ho visto su alcuni verbali dei vecchi progetti che lo hanno chiarito questo punto) da noi, in alcuni punti del documento e' in un modo in altri in un altro.
**sono le norme di progetto che danno le specifiche per questo genere di cose, al momento non abbiamo uno standard da seguire finché non sarà completato il documento!**

ho ri-fornito il file al gruppo degli analisti, segnalati gli errori e corretti alcuni, aspetto anche loro approvazione per ricaricare il file, compito di @fraccorzo 

riga 3: "...anche gli studi di fattibilità dei capitolati che sono stati scartati, mostrando anche..."
credo sia meglio evitare ripetere le stesse parole, "anche anche" nella stessa frase, riformulare.
**provvedo!**
riga 16: i link dei pdf non sono clickabili, se non funzione solo a me, ignorare.
**la codifica è fatta bene! devi scaricare il pdf per testare i link!**
