### ISSUE TITLE
Redazione Verbale del 30/11/2018

### ISSUE THREAD

**Issue by sebacaccaro** [SWEightgroup/Colletta#16]

**Comment by sebacaccaro** [comment]
**Per i verificatori:** 
Controllare solo nella cartella del verbale 30/11. I file spostati/cancellati nell'latra cartella sono dovuti al fatto che ho meglio organizzato la cartella verbali

**Comment by gisachi** [comment]
@sebacaccaro 
 riga 59: errore di battitura, due volte parola "nella" .
aggiungi anche come parlato l'ananlizzatore per gli errori di grammatica, e' uno strummento che useremo.(non mi ricordo come si chiama)

**Comment by sebacaccaro** [comment]
@gisachi 
Corretto secondo indicative. Gli elenchi puntati ora sono uniformi al primo verbale.
