### ISSUE TITLE
Creazione Scheletro Studio di fattibilità

### ISSUE THREAD

**Issue by sebacaccaro** [SWEightgroup/Colletta#3]

**Comment by maga97** [comment]
Necessità di inserire codifica T1 in latex.

**Comment by DamienCg** [comment]
file SWEightStyle.sty riga 92, la seguente codifica \usepackage[T1]{fontenc} risulta commentata,  procedo al fix togliendo il commento, anche se, nei pdf generati dal mio Texmaker non insorgono problemi di leggibilità.

**Comment by gisachi** [comment]
Sezione "Scopo del prodotto" non ha senso da trgliere e completare almeno la parte introduttiva del documento per avere una minima visione per mandarlo avanti

**Comment by DamienCg** [comment]
sezione 1.2 "Scopo del prodotto" in studio fattibilità, come dice @gisachi forse può risultare ridondante con la descrizione del capitolato scelto! chiedo approvazione da @sebacaccaro per la rimozione
ps
tengo il testo in locale, può servire per la descrizione di C2

**Comment by sebacaccaro** [comment]
@DamienCg 
@gisachi 
Rimozione approvata, tanto andrà tutto nello studio di c2. Se proprio volgiamo i sommelier, facciamo un paragrafetto dove spieghiamo che abbiamo scelto c2.

**Comment by gisachi** [comment]
verificato [https://github.com/SWEightgroup/Colletta/blob/C2/RR%20-%20SWEight/studio_fattibilita/sez/RegistroModifiche.tex](url)
non capisco perche per ogni branch ci sono gli stessi file, magari sarebbe meglio tenerli su una cartella unica o verra' risolto al merge...
Registro modifiche: leggendo le correzioni del prof. di vari doc degli anni scorsi, li piace di piu' vedere come collonna di chi ha fatto un'azione chiamata: "Nominativo" rispetto a "Autore" suggerisco di cambiarlo.

**Comment by DamienCg** [comment]
@gisachi , va bene posso anche cambiarlo! in quale correzione hai visto ciò?

**Comment by DamienCg** [comment]
cambiato da autore a nominativo!
